alias api='tmux new-session -d -s api "bash ./start.sh"'
alias 4h='tmux new-session -d -s 4h "bash ./4h.sh"'
alias 5m='tmux new-session -d -s 5m "bash ./5m.sh"'
alias 2h='tmux new-session -d -s 2h "bash ./2h.sh"'
alias 15m='tmux new-session -d -s 15m "bash ./15m.sh"'
alias 30m='tmux new-session -d -s 30m "bash ./30m.sh"'